name: GetPing
main: SVega9848\GetPing\Core\Main
version: 0.1.0
api: 4.1.0
author: SVega
description: Get your ping!

permissions:
  getping.cmd:
    description: Allows you to use the Ping command!
    default: op
